/**
 * English copy for the code-level credits on /references.
 *
 * Keyed by `credit.repo` (stable, unlike display names). Every entry mirrors
 * the Chinese data in `credits.ts`: same array order, same length, same
 * `licenseNote` presence. `credits.test.ts` checks that a translation exists
 * for every credit and that the shapes match; unmatched entries fall back to
 * the Chinese text at render time.
 */

export interface CreditTextEn {
  borrowed: string[]
  declined?: string[]
  licenseNote?: string
}

export const CREDITS_EN: Record<string, CreditTextEn> = {
  'https://github.com/laogou717/md-wechat': {
    borrowed: [
      'External links turned into footnotes. WeChat Official Accounts keep only clickable links on the mp.weixin.qq.com domain; every other external link is stripped outright by the editor at paste time, with the text left behind and the URL entirely lost. The link_footnote rule in upstream src/lib/renderer.js:523 swaps link_open for span_open (keeping the link’s visual styling but no longer an <a>), appends a superscript [n] after the link text, and collects the URL into the “References” section at the end of the article; WeChat-internal links are unaffected. We landed this in src/lib/render.ts: an isFootnotable check + createLinkRegistry collection + the theme’s footnotes() output. Because we have our own semantic IR, doing this at the render layer is enough; there is no need to touch markdown-it’s token stream.',
      'The fallback path for rich-text copying. Upstream legacyCopy in src/lib/clipboard.js: an off-screen contentEditable div (position:fixed; left:-9999px) + Range.selectNodeContents + execCommand("copy") + removed when done. Our src/lib/clipboard.ts is the same fallback, and the primary path is likewise the ClipboardItem text/html + text/plain dual channel.',
    ],
    declined: [
      'Its IndexedDB short-reference pipeline for images (src/lib/imagedb.js: bytes go into IndexedDB, the document keeps only a local: short reference, and it is restored to a data URI before copying). Our images go through Cloudflare R2 + img:<key>, so when a draft syncs across devices the images are there too; a data URI would stuff several MB of base64 into the body, easily blowing past the limits on the WeChat paste path.',
      'justifiedWidths, its justified multi-image grid (src/lib/renderer.js:224), and the companion aspect-ratio + object-fit:cover cropping (:635). Cropping to a fixed ratio cuts away image content, which violates our WeChat red lines.',
      'Its markdown-it core ruler rewrite system (list_flat to flatten lists, block_context to record block-level ancestors, gallery for image grids). The actual “token flattening” upstream is about lists, not tables; our parser produces the semantic IR directly, with no token stream to rewrite, so this mechanism has no foothold on our side.',
    ],
  },
  'https://github.com/doocs/md': {
    licenseNote:
      'The LICENSE body reads “DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE, Version 2, December 2004”, and the copyright line is Copyright (C) 2025 Doocs <admin@doocs.org>. This is an extremely permissive, public-domain-style licence with no copyleft, but the SPDX identifier is not MIT, and the licence name contains profanity — our stance is to record its real name, WTFPL v2, as-is, without rewriting it.',
    borrowed: [
      'Two-way sync scrolling switched to “block mapping” instead of total-height percentage. The doc comment in upstream apps/web/src/composables/useScrollSync.ts reads, verbatim, "Uses block-based mapping (not simple pixel ratio) so large content skew between panes stays accurate", and its companion apps/web/src/lib/preview/scroll-sync-blocks.ts splits the source document on blank lines and maps block indices proportionally. Our src/lib/sync-scroll.ts is an independent implementation of the same idea: block boundaries come from the parser semantic IR’s line/lineEnd, progress within a block is interpolated (progressInBlock / lineAtProgress), and fillBlockOffsets fills the holes where “this block rendered no element”. The idea comes from upstream; no code was moved over.',
      'Scroll events are funneled through a single requestAnimationFrame before the mapping math runs. Upstream useScrollSync.ts uses rAF to clear the isSyncingFromEditor / isSyncingFromPreview flags, swallowing the echo of its own programmatic scroll; our src/hooks/useSyncScroll.ts puts the whole mapping inside rAF and uses a 110ms idle window to decide which side owns sync, so the two panes do not drag each other around.',
      'How formulas are produced. Upstream takes the same MathJax tex-svg + fontCache:"none" road as wenyan-core (doocs at packages/core/src/utils/mathjax.ts:56), and the two independently confirm that SVG produced this way survives the WeChat paste path; we have landed on that route in src/lib/math.ts, with the details recorded under the wenyan-core entry.',
    ],
    declined: [
      'Its persistence layering (apps/web/src/storage/: an IndexedDB engine + engines/ + repositories/ + migrate/ + quota.ts). We first recorded it as “not doing it”: we already had localStorage drafts + server-side SQLite double-writes, and inserting another layer would only add one more source of truth. Later we changed our minds, and it was the same reason that overturned it: the body is the only thing that can grow without bound (a long article with a pasted table reaches the MB range), and localStorage setItem throws when full while the old code swallowed the exception — the editor kept accepting keystrokes as usual, and after a refresh the body reverted to the previous version. Now we split along the same line: the body goes into IndexedDB (src/lib/body-store.ts, falling back to localStorage when IndexedDB is unavailable), while the small things — index, settings, recycle bin — are still stored in localStorage (src/lib/store.ts); every write failure goes into persistenceStatus(), surfaced by the top-bar status slot and a toast. Upstream’s engines / repositories layering was not copied — what we wanted was “if it cannot be written, that has to be visible”, not one more layer of abstraction.',
      'Its way of decoupling input from re-rendering. Upstream is Vue and goes through debounce (apps/web/src/lib/debounce.ts); we are React and use useDeferredValue + useMemo (src/pages/EditorPage.tsx:135-141). Same goal, unrelated mechanism, so it is recorded as a reference rather than a port.',
      'Its monorepo split across clients (apps/web, apps/vscode, apps/utools, apps/api + packages/core, md-cli, mcp-server). We are a single Vite app; splitting into packages now would be over-engineering.',
      'Its inline-SVG route for mermaid (packages/core/src/extensions/mermaid.ts, 147 lines + packages/core/src/utils/wechat-svg.ts, 1434 lines). To make mermaid SVGs survive the WeChat paste path, upstream manually rewrites the HTML tags inside <foreignObject> into real SVG <text>/<tspan> (computing x/y/text-anchor/centering/multi-line dy/the background rect for edgeLabel by hand), pushes overlapping labels on bidirectional edges apart along the main axis, clamps a minimum font size under viewBox scaling (deliberately leaving em/rem/% units untouched), then computes the real pixel width/height, writes them into width/height and caps them at 677px. This sanitizing depends on getComputedStyle / getBBox / getTotalLength / getPointAtLength — all APIs that only exist on a live DOM — and it assumes styles have already been inlined by juice; its render timing is also async backfill (the renderer returns a placeholder div first, and once mermaid.render finishes, document.getElementById(id).innerHTML = svg). Our render chain is pure functions returning a string (renderDoc → theme templates → a one-shot dangerouslySetInnerHTML replacement), so adopting this would mean letting React’s vdom and manual DOM edits coexist — equivalent to giving up “the preview is the exact string you copy out”. So we took another route: mermaid → SVG → canvas → PNG → the existing image upload pipeline → a plain <img>, which naturally satisfies every red line, and it also lands in the image library automatically, where it can be tracked and re-cropped. The cost: the text in the image is not selectable, dark mode does not follow, and changing a single word means re-uploading.',
    ],
  },
  'https://github.com/alchaincyf/huasheng_editor': {
    borrowed: [
      'Four gates before pasting rich text. Upstream at app.js:2679-2852, in this order: plain text shaped like an [Image #N] placeholder is rejected outright, with a hint to switch to a screenshot tool / browser copy / drag and drop → when isMarkdown(text) (:2783) hits, the source is inserted as Markdown with no HTML conversion → isIDEFormattedHTML(html, text) (:2812) recognizes VS Code / Ace signatures (meta charset, ace_line, Consolas|Monaco|Menlo|Courier monospace fonts) plus two structural heuristics → isMainlyCode (:2718) recognizes whole blocks of code, “has pre/code but no p/div semantic tags”. This is the key protection against “copied from another Markdown editor, Turndown escapes **bold** into \\*\\*bold\\*\\*”. We landed it in src/lib/rich-paste.ts: gate 1 looksLikeMarkdown/markdownScore, gate 2 IDE syntax highlighting, gate 3 whole-block code into a fence, gate 4 placeholder rejection, with shouldConvertHtml as the combined exit. We changed the scoring — upstream is a flat count of “2 or more hits out of 13 patterns”, where two weak signals can decide the case; we weight strong vs weak signals (rich-paste.ts:60-115, the code comment reads, verbatim, "Weights mirror upstream huasheng_editor\'s isMarkdown"), so a block-level structure (fence, heading, image, table, container, ==mark==, link) can decide on its own, while purely inline clues must have a partner.',
      'How Turndown is configured. Upstream app.js:2557-2629 uses keep([\'table\',\'thead\',\'tbody\',\'tfoot\',\'tr\',\'th\',\'td\']) to keep the table structure, addRule(\'table\') for custom table output, and addRule(\'image\') to pull images out of the stream onto a separate upload path. We landed it in createService at src/lib/rich-paste.ts:810-1010: addRule lays out a full set of rules — dialectHeading / dialectMark / dialectStrikethrough / dialectLink / dialectImage / dialectPre / dialectListItem / dialectTable* / dialectBlockquote / dialectCenter — converting HTML directly into our own WeChat dialect rather than generic Markdown; before conversion, cleanHtmlSource (:344-) strips Word conditional comments and VML, <?xml?>, Office namespace tags (<o:p>, <w:WordDocument>), Mso* classes, and data-*/aria-* attributes. Upstream pulls turndown@7.2.0 from jsDelivr on demand at runtime (ensureTurndown, :2530); we bundle turndown + turndown-plugin-gfm.',
      'Image compression strategy. Upstream class ImageCompressor at app.js:243-330 scales to a 1920 longest edge and re-encodes through Canvas (transparent PNGs get a white background laid down before drawImage), and if the compressed result is larger than the original it falls back to the original file; before copying to WeChat there is a second pass, recompressForClipboard (app.js:2195-2230, longest edge 1200 / quality 0.6). We landed it in src/lib/image-compress.ts and extended it: the longest edge changed from upstream’s fixed 1920 to 2048 derived from the real width of WeChat body text (a 677px container minus 20px padding = 657 CSS px, × 3 DPR ≈ 1971, rounded up to a power of two), and the two fixed tiers became the ladder “800 KB target size + quality stepping down from 0.9 by 0.1 to a 0.6 floor” (:24-50, the loop at :283). Upstream’s “use the original if the result got bigger” check survives as the grew flag (:303). Upstream has no target-size dimension; the ladder is ours.',
    ],
    declined: [
      'Its multi-image grid with a fixed 360px container height + object-fit:contain + a gray background (app.js:1676-1722). The fixed height leaves large gray bands on either side of portrait images, and it violates our WeChat red lines.',
      'Its overall rendering route: markdown-it → HTML string → DOMParser → appending STYLES[theme].styles[selector] per selector onto every matching element’s style (applyInlineStyles, app.js:1352-1394). Themes there are a “selector → style” lookup table; ours are template functions — an order of magnitude apart in expressiveness.',
      'Its build-free single-file project shape (app.js at 3600+ lines, index.html at 2100+ lines, DEBUG = true hardcoded, console.log all over the screen).',
    ],
  },
  'https://github.com/din4e/MDInline': {
    borrowed: [
      'Library choice and load timing for DOCX import. extractDocxHtml in upstream frontend/src/lib/import/docx.ts converts to HTML with mammoth, deliberately via dynamic import, the stated reason being “mammoth is big, and only needed when the user actually imports a .docx”. We landed it in docxToDocxImport at src/lib/import-export.ts:439-487: likewise await import(\'mammoth\'), for exactly the same reason (the comment at :440-444 says a static import would push about 600 KB of DOCX/XML machinery into the entry chunk, while dynamic import lets Vite carve out a separate chunk, so the first screen does not pay for a feature most sessions never use). Upstream extractDocxHtml returns only an HTML string and does not handle images; the image half is ours — convertImage overrides mammoth’s default base64 inlining, collects each image into images[] and leaves an ![alt](docx-import:N) placeholder in the Markdown (:366-380, :474-483), after which replacement is by name rather than by position, so even two images sharing the same alt are not mismatched. The placeholder is deliberately not img:<key>, because Materials.tsx scans that protocol to decide “which images are still in use”, and a placeholder waiting for upload must not be counted. We also layered on a mammoth styleMap (:407-415) that maps Word’s Title to h1 and Quote / Intense Quote to blockquote, connecting to the article title and quote card in our dialect. The HTML→dialect conversion is an injected HtmlToMarkdown, whose actual implementation reuses rich-paste.ts, avoiding a second, worse copy left behind.',
      '(planned reference) useClampedNumber, frontend/src/components/controls.tsx:36. A slider and a number input share one clamped value: an out-of-range intermediate state is allowed while typing (otherwise, wanting to type 16 would be clamped to min the moment "1" is pressed), and it clamps back into [min, max] only on blur or when the slider is released. Our typography parameter panel does not have this kind of linked control yet.',
    ],
    declined: [
      'ThemeConfig + runtime CSS-string themes (the type definitions in frontend/src/lib/theme.ts; lib/css.ts assembles it into one long CSS string, with every selector hanging under .mdcss). A data-driven theme can only express scalars like font size, color, spacing and font weight; it cannot express the structural differences in our themes (quote card, citation box, auto-numbered sections, carousel frames, byline block). Introducing it would flatten the theme capability to 5%.',
      'Its juice post-hoc CSS inlining flow (frontend/src/lib/inline.ts, juice.inlineContent). Its copy root node is <div class="mdcss">, and WeChat strips class attributes and non-whitelisted tags — producing class-carrying HTML first and relying on juice to inline afterwards does not hold on the WeChat paste path. Our theme functions output <section>/<p> + inline style directly, so the post-hoc inlining step is unnecessary from the root.',
      'Its hand-rolled DOCX/RTF parser under frontend/src/lib/word/ (docx.ts 168 lines + parse.ts 347 lines + rtf.ts 196 lines + ir.ts 79 lines + worddoc.ts 33 lines, about 820 lines in total). mammoth already covers the fidelity we need; maintaining our own OOXML parser is not a good trade.',
      'Its “WeChat-safe attribute guard”. Checked for real, it turned out to be both overly conservative and not actually holding, so we switched to emitting only whitelisted tags and inline styles from the theme functions, replacing after-the-fact filtering with constraints on the producing side.',
    ],
  },
  'https://github.com/caol64/wenyan-core': {
    licenseNote:
      'Apache-2.0 carries a patent grant and NOTICE obligations: if we ever copy its code directly in the future (rather than only borrowing ideas), we must keep the full LICENSE text and the copyright notice in distributions and state which files we changed. The copy under LICENSES/ exists precisely for that obligation. The LICENSE files of the wenyan, wenyan-core and wenyan-ui repositories are byte-identical (md5 d229da563da18fe5d58cd95a6467d584), so the licensing is consistent.',
    borrowed: [
      'MathJax SVG math formulas, src/core/parser/mathjaxParser.ts (107 lines). mathjax-full + liteAdaptor() runs tex2svg in a pure-JS environment, and the key setting is fontCache: options.fontCache ?? "none" — every SVG carries its complete path definitions, referencing neither a shared <defs> nor external fonts or CSS. This is the precondition for formulas surviving the WeChat paste path. Our src/lib/math.ts is an independent implementation of the same configuration, with an added PACKAGE_VERSION global to bypass the eval-produced require in components/version.js (there is no require in the browser), and with formatError / compileError turning bad TeX into a thrown error instead of MathJax’s default red merror box — that box carries a data-mjx-error attribute and a mirrored <text> node and would be pasted into the body as-is. How formulas actually behave in the WeChat backend has been measured for real; see the first declined item.',
    ],
    declined: [
      'Its WeChat HTML cleanup rules, src/core/renderer/wechatPostRender.ts (103 lines). Testing confirmed two of the four are unnecessary for us: splitting a bare SVG out of mjx-container and moving width/height into style (the stated reason being “WeChat does not recognize SVG width/height attributes”), and wrapping every <li>’s child nodes in a <section>. On 2026-10-07 we generated probes from real theme code and the author pasted them for real in the WeChat backend: MathJax output as-is (ex units + currentColor) survived intact in all three variants, and bare <li> with inline-style runs was not split onto two lines either. So we do not change a single character of the SVG dimensions (hand-converting ex→px would come out about 10% too small); we only add an explicit color on the wrapper to resolve currentColor (defaultMath in src/lib/theme-fallbacks.ts); among the 9 themes, the 5 that use bare <li> also need no changes. Of the remaining two rules, block-level formula parent text-align:center is already what our defaultMath does, and for keeping code block indentation we achieve the same with white-space:pre-wrap (codeBlock in themes.ts), with no \\n → <br> replacement.',
      'Its core / ui / cli / mcp package split + a five-way package.json exports (. / ./wrapper / ./publish / ./wechat / ./http). It splits because it has five separately distributed products (mac App Store, Windows/Linux, CLI, MCP, Web); we have a single Vite app. What is genuinely worth learning is its way of drawing the “environment adaptation by injection” boundary (HttpAdapter / TokenStorageAdapter / MermaidRenderer / GetInputContentFn) — our resolveImg / resolveMath / resolveDiagram already do the same shape, so there is no need to introduce the package structure.',
      'Its Node facade for CLI/MCP (renderAndPublish / renderAndPublishToServer in src/node/wrapper.ts, plus JSDOM to supply the DOM). This is the most direct reference for when we actually build an Agent publishing channel, but that entry point does not exist yet.',
    ],
  },
  'https://github.com/caol64/wenyan-ui': {
    borrowed: [
      'A host/UI boundary built on “injection points” rather than inheritance: src/lib/hooks/*.ts is all setContext/getContext pairs (setUploadImage, setExportImageClick, setHandleFileOpen, setPublishArticleClick, ...), each get carrying a web fallback default (a dialog prompting “please use the desktop client”), and the host registers implementations once at startup. Our server-side capabilities (R2 images, the drafts library) are currently called straight from components via tRPC; when we later open the same render chain to an Agent or a non-browser entry point, this way of drawing the line — capabilities registered by the host, explicitly degraded when missing — can be borrowed directly.',
    ],
    declined: [
      'The SvelteKit component library itself. We are React 19 + Vite and cannot reuse the UI layer; we only borrow its boundary design.',
    ],
  },
  'https://github.com/caol64/wenyan': {
    borrowed: [
      'How the host side does one-time wiring: src/lib/setHooks.ts feeds the Swift bridge implementations (article storage, theme storage, settings storage, export, publish) into wenyan-ui’s injection points at app startup, and business components are completely unaware of it. A reference for when we later open a second host for the Agent/CLI.',
    ],
    declined: [
      'Its SvelteKit + desktop-shell product shape (mac App Store / Windows / Linux). We are a pure web app deployed on Cloudflare.',
    ],
  },
  'https://github.com/foolgry/editor': {
    licenseNote:
      'The LICENSE’s copyright line reads “Copyright (c) 2024 Huasheng (alchaincyf)”, byte-identical to the LICENSE of alchaincyf/huasheng_editor — because line 13 of the foolgry/editor README states outright that it is forked from huasheng_editor, and the LICENSE is inherited as-is. The parts foolgry added (sharing service, Go backend, Mermaid, Skill) have no separate copyright line and fall under the same MIT terms. Acknowledgements should call out both the fork relationship and the original copyright holder.',
    borrowed: [
      'The engineering of the Skill, skills/wechat-markdown-editor/SKILL.md (267 lines) → landed in skills/wechat-typesetter/ (SKILL.md + scripts/mopai.py, Python 3 standard library, zero dependencies). The conventions followed: the token lives only in .env inside the skill directory (gitignored, set-token tightens permissions to 600, and failures on Windows are swallowed); set-token is idempotent — repeating it replaces in place instead of stacking lines — and it also reads from stdin; “call first, configure after the error” — SKILL.md explicitly forbids running token-status or cat .env before every push, on the grounds that the normal path should not pay an extra round trip; error messages carry the absolute path of .env and the set-token command, so an agent that sees the error knows how to repair it; token-status shows only a mask; syncing to the global skill directory must exclude .env, otherwise the repository’s template would overwrite the user’s real token (which shows up as “it worked yesterday, today it suddenly asks for a token”). The paragraph order is copied too: the error text first, then how to configure.',
      'The client-side approach to local image upload, scripts/publish.py:300-339 (hand-written multipart), :342-358 (relative paths resolved against the directory of the Markdown file, not the cwd), :361-403 (the same path is uploaded only once, and one failed image does not break the publish — it goes into warnings) → landed in upload_image / resolve_local_ref / process_images in scripts/mopai.py. The rewrite target became our img:<key> (upstream writes absolute URLs); img: and docx-import: were added to the skip prefixes, since neither protocol is followed by a slash and an img://-style check like upstream’s would miss them.',
      'The server-side token model, server/main.go: only a digest is stored in the database, plaintext is returned only once at issuance (:1426, :1742-1744), revocation is a soft delete rather than DELETE (:1479-1498), failed credential checks never degrade to anonymous (:335), and the 401 body carries a self-service entry point (:1354-1363) → landed in api/lib/agent-auth.ts (constant-time comparison, 401 and 403 worded differently, every token carrying a name and scope) and api/agent-router.ts. At the P0 stage tokens come from the environment variable AGENT_TOKENS=name:token[:scope]; deleting one line equals revocation, so there is no tokens table yet; that table and the frontend management panel are left for P1 after open-sourcing.',
      'The 401 error contract (main.go:1345-1363 distinguishes “no credentials” from “invalid credentials” in wording) → every one of our error bodies is {error, hint}, and hint names the next action rather than a bare “unauthorized”.',
    ],
    declined: [
      'Anonymously readable share pages (the /s/<id> article page and the /p/<id>/<sid> project deep link, server/main.go:143-145). Our drafts library is isolated by owner, and an anonymous visitor cannot read a single character from the API; the finished article’s destination is the WeChat backend, not an address for people to read on the web. Building anonymous share pages would mean hosting public content ourselves, with id enumeration and crawlers to defend against — upstream’s ADR-0004 spends a whole paragraph on why it was forced to shut anonymous publishing down, and there is no need for us to walk into the same pit on purpose. To be clear, upstream does not open anonymous publishing either (:311, :335 explicitly require a token); our disagreement is only on the reading side.',
      'Browser and Agent sharing one set of endpoints and one Bearer token scheme (upstream does not distinguish internal from external; the only difference is where credentials are stored: browser localStorage, agent .env). We deliberately split into two doors: the browser keeps using tRPC + cookie session, and the agent uses plain REST under /api/agent/* + Bearer. The reason is that superjson’s wire format is extremely unfriendly to third-party clients (Date fields need hand-written metadata, errors are wrapped in a JSON-RPC envelope), while the Skill must be verifiable by any harness with a one-line curl; it also lets the two credential kinds carry different permissions and lifetimes.',
      'Doubling the human login password as an API token (upstream’s WXMD_LIST_PASSWORD fallback, main.go:1704-1728). Our ACCESS_KEY is the site login password, and also serving it as an API credential would blur what it actually is, while a single leak would invalidate every agent at once.',
      'The whole Project aggregation and attach/detach set (about 250 lines). Our counterpart is a flat drafts library that does not need a second aggregation dimension.',
      'Granting tokens the delete right (main.go:585-645). Our agents can only read and write; deletion is always an action a human performs in the web UI, and the recycle bin is managed by people too.',
      'Hardcoding the stylesheet into both the script and SKILL.md (the 27 keys at publish.py:51-79). Themes come and go, and two hand-synced copies will drift apart sooner or later, so mopai.py contains not a single theme name and always fetches GET /api/agent/themes live.',
      'Timestamps as optimistic locks. We originally planned to compare updatedAt the way upstream does, but testing showed docs.updatedAt lands in the database at second precision and carries the client clock, so two writes within the same second cannot be told apart — an agent would silently steamroll careful human edits. We switched to the first 16 hex digits of a content sha256 (hash / baseHash), which also turns “pushing the same content again” into an idempotent success instead of a false conflict.',
      'An MCP server. Upstream does not have one either (zero hits across the whole repository); our agent runs locally and can use a shell, and a zero-dependency script is more universal than MCP, which would also need per-harness configuration and stdio process lifecycle management.',
      'The huasheng_editor rendering route it kept after forking (selector lookup + applyInlineStyles). Same as the huasheng_editor entry.',
    ],
  },
}
